#!/bin/bash

gnome-terminal -e /home/dnav/Desktop/TicTacToe/src/Controller.py

rm /home/dnav/Desktop/TicTacToe/src/*.pyc

# rm /home/dnav/Desktop/TicTacToe/src/known_boards.txt
# touch rm /home/dnav/Desktop/TicTacToe/src/known_boards.txt