#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
	find ~/Desktop -name 'Controller.py' -print0 | xargs -0 python
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
	gnome-terminal -e /home/dnav/Desktop/TicTacToe/src/Controller.py

else
	echo This program only runs on OSX and Linux

fi