#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
	osascript -e 'tell app "Terminal"
    	do script "python /Users/dnavarro/Desktop/TicTacToe/src/Controller.py"
	end tell'
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
	gnome-terminal -e /home/dnav/Desktop/TicTacToe/src/Controller.py

else
	echo This program only runs on OSX and Linux

fi